version: '3.8'

services:
  db:
    image: postgres:15
    container_name: nest_postgres
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ml_network

  prometheus:
    build: 
      context: .
      dockerfile: Dockerfile.prometheus
    container_name: nest_prometheus
    restart: always
    ports:
      - "9090:9090"
    networks:
      - ml_network

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
      target: development
    container_name: nest_api
    restart: always
    ports:
      - "3000:3000"
      - "9464:9464"
    environment:
      # O docker-compose vai ler o .env do Jenkins e injetar os valores aqui!
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      SMTP_FROM: ${SMTP_FROM}
      FRONTEND_URL: ${FRONTEND_URL}
      PORT: 3000
    networks:
      - ml_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: ${VITE_API_BASE_URL}
    container_name: nest_frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - api
    networks:
      - ml_network

networks:
  ml_network:
    driver: bridge

volumes:
  postgres_data:
    external: true
    name: ml-estoque_postgres_data_prod
  