<template><ion-page><ion-content class="vivid-page"><div class="login-wrap"><main class="login-card vivid-card"><img src="/favicon.png" class="login-logo" /><h1>ML Estoque</h1><p>Gerenciamento de alta performance</p><AppField v-model="form.email" label="E-mail" placeholder="nome@empresa.com.br" :icon="mailOutline" /><PasswordField v-model="form.password" label="Senha" placeholder="••••••••" :icon="lockClosedOutline" /><div class="forgot-link-wrap"><router-link to="/forgot-password">Esqueci minha senha</router-link></div><div v-if="authStore.error" class="form-error">{{ authStore.error }}</div><button class="primary-button" :disabled="authStore.loading" @click="handleLogin">{{ authStore.loading ? 'Entrando...' : 'Acessar Sistema' }}</button><div v-if="authStore.biometricsAvailable" class="bio"><span>ou</span><button aria-label="Acessar com biometria" @click="handleBiometricLogin"><ion-icon :icon="fingerPrintOutline" /></button><p>Acessar com Biometria</p></div></main><footer>ML Estoque © 2026 • Infraestrutura de Logística Segura</footer></div></ion-content></ion-page></template>
<script setup lang="ts">
import { reactive, onMounted } from 'vue'; import { IonPage,IonContent,IonIcon,toastController,alertController } from '@ionic/vue'; import { fingerPrintOutline,lockClosedOutline,mailOutline } from 'ionicons/icons'; import AppField from '@/components/AppField.vue'; import PasswordField from '@/components/PasswordField.vue'; import { useAuthStore } from '@/stores/auth'; import { useRouter } from 'vue-router';
const authStore=useAuthStore(),router=useRouter(),form=reactive({email:'',password:''});
const handleLogin=async()=>{if(!form.email||!form.password)return toast('Preencha todos os campos','warning');if(await authStore.login(form)){if(authStore.biometricsAvailable&&!authStore.biometricsLinked){const alert=await alertController.create({header:'Ativar Biometria?',message:'Deseja usar biometria nos próximos acessos?',buttons:[{text:'Agora não',handler:()=>router.replace('/home')},{text:'Ativar',handler:async()=>{await authStore.enrollBiometrics(form);router.replace('/home')}}]});await alert.present()}else router.replace('/home')}};
const handleBiometricLogin=async()=>{const result=await authStore.loginWithBiometrics();if(result.success)router.replace('/home');else toast({'unavailable':'Biometria indisponível','not-linked':'Entre com sua senha para ativar a biometria','cancelled':'Autenticação cancelada','credentials-missing':'Vínculo expirado. Entre novamente','login-failed':authStore.error||'Falha no login'}[result.reason],'danger')};
const toast=async(message:string,color:string)=>{const t=await toastController.create({message,color,duration:2500});await t.present()}; onMounted(()=>authStore.initialize());
</script>
<style scoped>.login-wrap{min-height:100%;padding:48px 20px 24px;display:grid;align-content:center;gap:28px;background:radial-gradient(circle at top left,#201d42,var(--vivid-bg) 55%)}.login-card{padding:34px 28px;text-align:center}.login-logo{width:78px;height:78px;border-radius:18px;padding:8px;background:#0f172a;border:1px solid var(--vivid-outline)}h1{font-size:32px;margin:20px 0 4px;color:var(--vivid-text)}p{color:var(--vivid-muted)}.forgot-link-wrap{display:flex;justify-content:flex-end;font-family:"JetBrains Mono",monospace;font-size:12px;margin:-10px 4px 18px;color:var(--vivid-muted)}a{color:var(--vivid-primary-bright)}.bio{margin-top:28px;border-top:1px solid var(--vivid-outline);padding-top:18px}.bio>span{display:block;margin:-28px auto 18px;width:44px;background:var(--vivid-surface);color:var(--vivid-muted)}.bio button{width:76px;height:76px;border-radius:50%;background:transparent;border:2px solid #7d6389;color:var(--vivid-primary-bright);font-size:42px}.form-error{color:#ffb4ab;margin:10px}footer{text-align:center;color:#84798b;font:12px "JetBrains Mono",monospace}</style>
